import type {NextPage} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@src/styles/Home.module.css';
import {Button, Container} from 'react-bootstrap';
import {useEffect, useState} from 'react';
import Axios from 'axios';
import ItemList from '@src/components/ItemList';

const Home: NextPage = () => {
  const [list, setList] = useState<[]>([]);
  const API_URL = 'http://makeup-api.herokuapp.com/api/v1/products.json?brand=maybelline';

  useEffect(() => {
    getData();
  }, []);

  const getData = () => {
    Axios.get(API_URL).then(res => {
      console.log(res.data);
      setList(res.data);
    });
  };


  return (
    <Container>
      <Head>
        <title>Pawn demon</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <ItemList list={list} />
      </main>

    </Container>
  );
};

export default Home;

function useSate(): any[] {
  throw new Error('Function not implemented.');
}

